<a href="https://colab.research.google.com/github/1234-ad/1234-ad/blob/main/Hand%20Sign%20Detection%20using%20CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###The Major Project

This project is made by our group having group members:-


#1. Sparsh Gupta  
#2. Aditya Rastogi
#3. Ashay Chaudhari
#4. Yash Chindam
#5. Radhika Khandelwal
#6. Aravinth K
#7. SURYA R S

#Before checking this project plz upload csv file from your side as it might not show when i will share the link .And before moving to the project please read the below...


We have made the project till the model 1 as we aren't able to connect with the project details given to us.In details, it was given the X and Y files containimg the arrays of 0 and 1..we don't know what is the role of X and Y files in that..as the project is only related to hand sign detection so we don't understand to how to connect the image detection with these files.

We even try to reach the mentor but mentor only provided the information regarding the reading of these X and Y files which we have already done..rather then giving the link between these files and the hand sign image detection process. So,we are sorry that we are able to do this much project only due to lack of information.We hope you understand the situation....


In [ ]:
#required libraries
import math
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.python.framework import ops
import keras
from keras import backend as k
from tensorflow.keras.utils import to_categorical

In [ ]:
x= np.load('/content/X.npy')
print("The data is:")
print(x)

The data is:
[[[0.46666667 0.4745098  0.47843137 ... 0.5176471  0.5137255  0.5019608 ]
  [0.49803922 0.4862745  0.4862745  ... 0.5254902  0.5176471  0.50980395]
  [0.54509807 0.49411765 0.49019608 ... 0.5294118  0.5254902  0.5137255 ]
  ...
  [0.5019608  0.5137255  0.5176471  ... 0.5529412  0.54509807 0.53333336]
  [0.49803922 0.5058824  0.5137255  ... 0.54509807 0.53333336 0.52156866]
  [0.49019608 0.49803922 0.5019608  ... 0.5294118  0.52156866 0.50980395]]

 [[0.59607846 0.60784316 0.61960787 ... 0.4627451  0.4509804  0.44313726]
  [0.60784316 0.61960787 0.6313726  ... 0.4745098  0.4627451  0.4509804 ]
  [0.6156863  0.627451   0.6431373  ... 0.4862745  0.4745098  0.4627451 ]
  ...
  [0.50980395 0.5176471  0.5254902  ... 0.40392157 0.39607844 0.3882353 ]
  [0.5019608  0.50980395 0.5176471  ... 0.4        0.39215687 0.38431373]
  [0.49411765 0.5058824  0.50980395 ... 0.3882353  0.38039216 0.37254903]]

 [[0.5882353  0.6039216  0.61960787 ... 0.53333336 0.5137255  0.5019608 ]
  [0.5921

In [ ]:
print(x.dtype)

float32


In [ ]:
y = np.load('/content/Y.npy')
print("The data is:")
print(y)

The data is:
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
print(y.dtype)

float64


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(f1,test_dataset,test_size = 0.3)
print("x_train",x_train.shape)
print("x_test",x_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

x_train (1443, 64, 64)
x_test (619, 64, 64)
y_train (1443, 10)
y_test (619, 10)


### **Building Multiclass ANN Classification Model**

In [ ]:
#Normalization of dataset Pixel values of the images will be from 0 to 255, so we'll normalize the dataset by dividing pixel values by 255.
x_train=x_train/255
x_test=x_test/255

In [ ]:
#converting class values to binary class metric for training and test set
y_train = tf.keras.utils.to_categorical (y_train, num_classes=None)
y_test=tf.keras.utils.to_categorical (y_test,  num_classes=None)
print ("number of training examples = " + str(x_train.shape[0]))

print ("number of test examples =  " + str(x_test.shape[0]))

print ("X_train shape:  " + str(x_train.shape))

print ("Y_train shape:  " + str(y_train.shape))

print ("X_test shape: " + str(x_test.shape))

print ("Y_test shape:  " + str(y_test.shape))


number of training examples = 1443
number of test examples =  619
X_train shape:  (1443, 64, 64)
Y_train shape:  (1443, 10, 2)
X_test shape: (619, 64, 64)
Y_test shape:  (619, 10, 2)


In [ ]:
# from tensorflow.keras import layers
# x_train= layers.InputLayer(input_shape=(2,2,1))
# conv1 = layers.Conv2D(3,(2,2))
# X= np.ones((2,2))
# X =X.reshape(1,X.shape[0],X.shape[1],1) # shape of X is 4D, (1, 2, 2, 1)
# conv1(x_train(X))
# x_train = np.array(X)
y_train.shape

(1443, 10, 2)

In [ ]:
#importing all modules from keras to create CNN Architecture
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Activation
from keras.layers import Flatten,Dense,Dropout
from tensorflow.keras.layers import Dense,ReLU,LeakyReLU
from tensorflow.keras.activations import softmax,elu,tanh,linear
from tensorflow.keras.optimizers import Adam,RMSprop,SGD,Adadelta,Adagrad

In [ ]:
# m1 model

In [ ]:
#we have to change the model for 3d input , below model is for 4d input
# model=Sequential() #initialize Sequential model
# model.add(Conv2D(8, (4,4), strides=(1,1),padding='same'))
# model.add(Activation ('relu'))
# model.add(MaxPooling2D((8,8), strides=(8,8), padding='same'))
# model.add(Conv2D(16, (2, 2), strides=(1,1), padding='same'))
# model.add(Activation ('relu'))
# model.add(MaxPooling2D((4,4), strides=(4,4), padding='same'))
# model.add(Flatten())
# model.add(Dense(6,))
# model.add(Activation ('softmax'))
m1 =Sequential()
m1.add(keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
m1.add(keras.layers.MaxPooling2D((2, 2)))
m1.add(keras.layers.Conv2D(64, (3, 3), activation='relu'))
m1.add(keras.layers.MaxPooling2D((2, 2)))
m1.add(keras.layers.Conv2D(64, (3, 3), activation='relu'))
m1.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_9 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_10 (Conv2D)          (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_11 (Conv2D)          (None, 4, 4, 64)          36928     
                                                                 
Total params: 56,320
Trainable params: 56,320
Non-trai

In [ ]:
m1.add(keras.layers.Flatten())
m1.add(keras.layers.Dense(64, activation='relu'))
m1.add(keras.layers.Dense(10))
m1.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_9 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_10 (Conv2D)          (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_11 (Conv2D)          (None, 4, 4, 64)          36928     
                                                                 
 flatten_4 (Flatten)         (None, 1024)             